// Frases para o pé: citas célebres sobre a radio (traducidas ao galego e
// atribuídas) xunto con outras sobre os beneficios da radio escolar.
export const QUOTES: string[] = [
  "A radio é o teatro da mente; a televisión, o teatro da mente baleira. — Steve Allen",
  "A televisión dá a todos unha imaxe; a radio fai nacer un millón de imaxes en un millón de mentes. — Peggy Noonan",
  "A radio é o medio máis íntimo e persoal do mundo. — Harry von Zell",
  "A radio afecta á xente de forma moi íntima, de ti a ti. — Marshall McLuhan",
  "A radio marca os minutos da vida; o xornal, as horas; o libro, os días. — Jacques de Lacretelle",
  "O poder da radio non é falar a millóns, senón falarlle íntimamente a cada un deles.",
  "A radio é máis poderosa canto máis se achega á forma en que falamos uns con outros.",
  "Na radio, a imaxe ponna quen escoita.",
  "A radio é a compañía que se escoita coa imaxinación.",
  "Un mundo sen radio sería un mundo un pouco máis xordo.",
  "A radio non se ve, pero faise ver na mente de quen a escoita.",
  "A radio é a maxia de crear imaxes só co son.",
  "Facer radio na escola é aprender a escoitar, pensar e dicir.",
  "A radio escolar dálle voz ao alumnado e oídos á comunidade.",
  "Detrás de cada locutor hai un guión, e detrás de cada guión, moitas horas de equipo.",
  "Ler en voz alta para outros é a mellor escola de lectura.",
  "A radio convence á timidez de que tamén ten cousas que contar.",
  "Quen aprende a falar diante dun micrófono, aprende a falar diante da vida.",
  "Na radio escolar non hai erros: hai ensaios.",
  "A radio fai do galego unha lingua que se escoita, se goza e se comparte.",
  "Unha boa entrevista comeza por saber escoitar.",
  "A radio ensina que toda voz, por pequena que sexa, merece ser escoitada.",
  "Preparar un programa é investigar, decidir e atreverse.",
  "A radio escolar transforma a curiosidade en contido, e o contido en aprendizaxe.",
  "Falar para que te entendan é o primeiro paso para entenderte cos demais.",
  "A radio dá sentido ao que se escribe na aula.",
  "Compartir micrófono é aprender a compartir a palabra.",
  "A radio escolar é unha porta aberta entre a escola e o mundo.",
  "Cada emisión é un pequeno ensaio de cidadanía.",
  "A radio ensina a respectar a quenda e o silencio dos demais.",
  "Na radio, o traballo de cada quen só brilla se brilla todo o equipo.",
  "A voz é o primeiro instrumento; a radio, o seu escenario.",
  "A radio escolar fai grande o que se aprende, porque o fai público.",
  "Escoitar antes de falar: a primeira regra da radio e da convivencia.",
  "Cando soa a sintonía, a aula convértese en estudio.",
  "A radio escolar deixa pegada: é a voz da infancia que medra.",
  "Contar o que pasa no centro é aprender a mirar o mundo.",
  "A radio ensina a coidar cada palabra, porque cada palabra conta.",
  "Un micrófono aberto é unha invitación a participar.",
  "A radio achega as familias á escola a través do son.",
  "Locutar é aprender a respirar, a pausar e a emocionar.",
  "A radio escolar celebra todas as voces e todos os acentos.",
  "Da idea ao micrófono: a radio ensina a converter o pensamento en palabra.",
  "A radio é o xeito máis bonito de dicir «aquí estamos».",
  "Quen fai radio aprende que escoitar tamén é unha forma de falar.",
  "A radio escolar pon banda sonora á vida do centro.",
  "Cada programa é unha historia contada entre moitas mans e moitas voces.",
  "Equivocarse ao aire ensina a rir, respirar e seguir.",
  "A radio é o medio que mellor sabe acompañar.",
  "Na radio escolar, cada quen achega o seu talento á mesma voz.",
];

export function randomQuote(): string {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
