// 50 frases en galego sobre os beneficios educativos da radio escolar.
// Móstrase unha ao chou no pé, só cando hai espazo dabondo (ver CSS).
export const QUOTES: string[] = [
  "A radio escolar dálle voz a quen aínda está aprendendo a atoparse.",
  "Falar ao micrófono ensina a pensar antes de dicir.",
  "Na radio, escoitar é tan importante como falar.",
  "Cada programa é un exercicio de traballo en equipo.",
  "A radio converte a timidez en confianza.",
  "Ler en voz alta mellora coa práctica, e a radio é práctica con sentido.",
  "Detrás de cada locutor hai un guión escrito con coidado.",
  "A radio escolar achega a escola á comunidade.",
  "Improvisar con respecto tamén se aprende.",
  "Un micrófono aberto é unha porta á creatividade.",
  "Na radio, os erros tamén ensinan e fannos máis humanos.",
  "Contar o que pasa no centro reforza o sentimento de pertenza.",
  "A radio dá a palabra a todas as voces, non só ás máis altas.",
  "Preparar un programa é planificar, investigar e decidir.",
  "A radio escolar fai do galego unha lingua viva e cotiá.",
  "Escoitarse a un mesmo axuda a mellorar a dicción.",
  "Unha boa entrevista empeza por saber escoitar.",
  "A radio ensina a respectar a quenda de palabra.",
  "Crear xuntos un programa une máis que mil charlas.",
  "A radio transforma a información en aprendizaxe compartida.",
  "Cada efecto de son é unha pequena lección de creatividade.",
  "A radio dálle ritmo e música ás palabras.",
  "Falar para outros ensina a poñerse no seu lugar.",
  "A radio escolar fai visible o que se aprende na aula.",
  "Un guión ben feito é a metade dun bo programa.",
  "A radio anima a investigar antes de opinar.",
  "Locutar ensina a controlar os nervios e a respiración.",
  "Na radio, cada quen achega o seu talento.",
  "A radio é un xeito divertido de coidar a lingua.",
  "Compartir micrófono é compartir responsabilidade.",
  "A radio converte a curiosidade en contido.",
  "Aprender a sintetizar é aprender a comunicar.",
  "A radio escolar abre a escola ao mundo e o mundo á escola.",
  "Detrás dun bo programa hai moitas escoitas atentas.",
  "A radio ensina que toda voz merece ser escoitada.",
  "Preparar unha noticia é aprender a distinguir o importante.",
  "A radio fomenta a lectura cun obxectivo: ser entendido.",
  "Falar con claridade é un agasallo para quen escoita.",
  "A radio dá sentido ao que se escribe na aula.",
  "Cada emisión é un ensaio de cidadanía.",
  "A radio escolar celebra a diversidade de voces.",
  "Equivocarse ao aire ensina a rir dun mesmo e seguir.",
  "A radio ensina a traballar contra o reloxo con calma.",
  "Un programa de radio é unha historia contada entre moitos.",
  "A radio achega a cultura propia a toda a comunidade.",
  "Escoitar antes de falar é a primeira regra da radio.",
  "A radio fai da palabra unha ferramenta de respecto.",
  "Crear radio é aprender facendo, e gozar aprendendo.",
  "A radio escolar deixa pegada: a voz da infancia que medra.",
  "Hoxe locutores na escola, mañá cidadáns que saben comunicar.",
];

export function randomQuote(): string {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
